# Generated by Django 6.1 on 2026-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='default_students_per_page',
            field=models.PositiveSmallIntegerField(default=15, help_text='Default number of students shown per page in faculty class/attendance views.'),
        ),
    ]
