# Generated by Django 6.1 on 2026-09-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemconfig_default_students_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
