# Generated by Django 6.1 on 2026-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The specific date this absence applies to.')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for absence.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('reassigned', 'Reassigned'), ('self_study', 'Self-Study / Makeup Flagged')], default='pending', max_length=25)),
                ('confirmation_deadline', models.DateTimeField(blank=True, help_text='Deadline by which the proposed substitute must confirm.', null=True)),
                ('is_makeup_candidate', models.BooleanField(default=False, help_text='Set True when no substitute found; flags this period for a makeup class.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opted_in', models.BooleanField(default=True, help_text='Whether this faculty has opted in to receive substitution requests.')),
                ('notes', models.TextField(blank=True, help_text='Optional: general availability notes (e.g. not available Mon mornings).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Availability',
                'verbose_name_plural': 'Faculty Availabilities',
            },
        ),
        migrations.CreateModel(
            name='SubstitutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_random_tiebreak', models.BooleanField(default=False, help_text='True if this substitute was chosen via random tie-break (for audit transparency).')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
