# Generated by Django 6.1 on 2026-08-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absencereport',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencereport',
            name='proposed_substitute',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_substitutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencereport',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports', to='core.timetableslot'),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='faculty',
            field=models.OneToOneField(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substitutionrecord',
            name='absence_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_record', to='absence.absencereport'),
        ),
        migrations.AddField(
            model_name='substitutionrecord',
            name='substitute_faculty',
            field=models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='substitution_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='absencereport',
            unique_together={('faculty', 'timetable_slot', 'date')},
        ),
    ]
