# Generated by Django 6.1 on 2026-09-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absencereport',
            name='assigned_substitute',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_substitutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='absencereport',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED — kept for backward compat. Use SubstituteRequest instead.', null=True),
        ),
        migrations.AlterField(
            model_name='absencereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned — No Substitute'), ('self_study', 'Self-Study / Makeup Flagged'), ('pending_confirmation', 'Pending Confirmation (legacy)'), ('reassigned', 'Reassigned (legacy)')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='SubstituteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absence_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_requests', to='absence.absencereport')),
                ('requested_faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_substitute_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substitute Request',
                'verbose_name_plural': 'Substitute Requests',
                'ordering': ['created_at'],
                'unique_together': {('absence_report', 'requested_faculty')},
            },
        ),
    ]
