# Generated by Django 6.1 on 2026-08-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('substitution_request', 'Substitution Request'), ('class_reassigned', 'Class Reassigned'), ('self_study', 'Self-Study Fallback'), ('makeup_candidate', 'Makeup Candidate Flagged'), ('announcement', 'Announcement'), ('assignment_reminder', 'Assignment Reminder'), ('attendance_alert', 'Attendance Alert'), ('risk_flag', 'Early-Warning Flag')], max_length=30)),
                ('message', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='PK of the related object (AbsenceReport, Assignment, etc.)', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Human-readable explanation: attendance %, missed submissions count, etc.')),
                ('attendance_pct', models.FloatField(blank=True, help_text='Attendance % at time of flagging.', null=True)),
                ('missed_submissions', models.PositiveSmallIntegerField(default=0)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
