# Generated by Django 6.1 on 2026-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_riskflag_course_announcement_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', help_text='Tracks the delivery pipeline: PENDING → SENT → DELIVERED → READ / FAILED', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('substitution_request', 'Substitution Request'), ('class_reassigned', 'Class Reassigned'), ('self_study', 'Self-Study Fallback'), ('makeup_candidate', 'Makeup Candidate Flagged'), ('announcement', 'Announcement'), ('assignment_reminder', 'Assignment Reminder'), ('attendance_alert', 'Attendance Alert'), ('risk_flag', 'Early-Warning Flag'), ('absence_marked', 'Absence Marked')], max_length=30),
        ),
    ]
